name: AnnualPassport
version: 0.20.3
main: com.magicaldreams.annualpassport.Main
api-version: 1.13
description: The Magicband plugin for magicaldreams
website: magicaldreams.us, github.com/nolant108
commands: